// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBase.Tables
{
    public partial class Student
    {
        public Guid StuId { get; set; }
        public string StuName { get; set; }
        public string StuEmail { get; set; }
        public string StuPhone { get; set; }
        public string Password { get; set; }
    }
}