// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBase.Tables
{
    public partial class Teacher
    {
        public Teacher()
        {
            Class = new HashSet<Class>();
        }

        public Guid TeaId { get; set; }
        public string TeaName { get; set; }
        public string TeaEmail { get; set; }
        public string TeaPhone { get; set; }

        public virtual ICollection<Class> Class { get; set; }
    }
}